baseURL = "https://hbina.github.io"
theme = "risotto"
title = "hbina page"
author = "Hanif Bin Ariffin"
copyright = "IDK what a copyright is"
languageCode = "en-us"
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "Hanif Bin Ariffin"
description = "Probably rambling about something."
logo = "favicon.ico"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/hbina"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:hanif.ariffin.4326@gmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/hanif-bin-ariffin-73057a8b/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

