baseURL = "https://hbina.github.io"
theme = "ananke"
title = "hbina page"
author = "Hanif Bin Ariffin"
copyright = "IDK what a copyright is"
languageCode = "en-us"
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"
